SCREEN_WIDTH = 480
SCREEN_HEIGHT = 480
GRID_SIZE = 20
GRID_WIDTH = int(SCREEN_WIDTH / GRID_SIZE)
GRID_HEIGHT = int(SCREEN_HEIGHT / GRID_SIZE)
SNAKE_START = (int(GRID_WIDTH / 2), int(GRID_HEIGHT / 2))

BACKGROUND_EVEN_COLOR = (84, 194, 205)
BACKGROUND_ODD_COLOR = (93, 216, 228)
